name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up tree-sitter
      uses: tree-sitter/setup-action/cli@v2
    - name: Run tests
      run: tree-sitter test
